version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.1.4-management
    container_name: rabbitmq-mcp-test
    ports:
      - "5672:5672"      # AMQP 端口
      - "15672:15672"    # Management UI 端口
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: